name: Build Docker Image
on:
  push:
    branches: ['**']
    tags: ['v*']

jobs:
  build:
    runs-on: Linux
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: registry.savvy.codes
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: registry.savvy.codes/${{ github.repository }}
          tags: |
            # branch event
            type=ref,event=branch,suffix=-{{sha}}
            # tag event
            type=ref,event=tag
            # latest when default branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          pull: true
          platforms: linux/amd64
          cache-from: type=local,src=/mnt/docker-registry/${{ github.repository }}
          cache-to: type=local,dest=/mnt/docker-registry/${{ github.repository }},mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
